version: "3.4"
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=file-processor'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=fileprocessor'
    ports:
      - '3307:3306'
  mqtt:
    image: 'eclipse-mosquitto:latest'
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./config:/mosquitto/config:rw
  file-processor:
    build:
      context: .
    environment:
      - spring_profiles_active=docker
    depends_on:
      - "mqtt"
      - "mysql"

