version: "3.4"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6377:6379"
    networks:
      - file-processor
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=file-processor'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=fileprocessor'
    ports:
      - '3307:3306'
    networks:
      - file-processor
  mqtt:
    image: 'eclipse-mosquitto:latest'
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./config:/mosquitto/config:rw
    networks:
      - file-processor
  file-processor:
    build:
      context: .
    environment:
      - spring_profiles_active=docker
    depends_on:
      - "mqtt"
      - "mysql"
    networks:
      - file-processor
  file-uploader:
    image: "ghcr.io/iubh-seminars-assignments/file-uploader:main"
    ports:
      - "5001:5000"
    depends_on:
        - "file-processor"
        - "mqtt"
        - "redis"
    networks:
      - file-processor
networks:
  file-processor:

